sudo: false
language: node_js
node_js:
  - "6"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn run test
  - yarn run build
after_success:
  - yarn run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
